version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123 # Replace with your actual root password
      MYSQL_DATABASE: gcpdb               # Your database name
    ports:
      - "3307:3306"                       # Maps MySQL port 3306 to host
    volumes:
      - mysql_data:/var/lib/mysql         # Persist MySQL data

volumes:
  mysql_data:
